<a href="https://colab.research.google.com/github/jbsnyder116/Data-Stuff/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('TitanicRB.csv')

In [4]:
df

,PassengerId,Name,Sex,Age,Pclass,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,3,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,3,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,S,1
4,5,"Allen, Mr. William Henry",male,35.0,3,S,0
...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,2,S,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,1,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,3,S,0
889,890,"Behr, Mr. Karl Howell",male,26.0,1,C,1
890,891,"Dooley, Mr. Patrick",male,32.0,3,Q,0

In [5]:
pd.crosstab(index = df['Sex'], columns=df['Survived'])

Survived    0    1
Sex
female     81  233
male      468  109

If sex = female, then we predict survived = 1

If sex = male, then we predict survived = 0

The error rate 190/891 = .213

In [6]:
pd.crosstab(index=df['Pclass'], columns=df['Survived'])

Survived    0    1
Pclass
1          80  136
2          97   87
3         372  119

If PClass = 1, then predict that they will survive

If PClass = 2, then predict that they will die.

If PClass = 3, then predict that they will die.

The error rate =  286/891 = .320

In [7]:
pd.crosstab(index=df['Embarked'], columns=df['Survived'])

Survived    0    1
Embarked
C          75   93
Q          47   30
S         427  217

If Embarked = C, then predict that they will survive

If Embarked = Q, then predict that they will survive.

If Embarked = S, then predict that they will die.

The error rate is 322/891 = .36

The final Rule Set:

If sex = female, then we predict survived = 1.
If sex = male, then we predict survived = 0.  This has the smallest/lowest error rate of .213.